// Export Functionality Module
// Handles exporting analysis results to various formats

class ExportManager {
    constructor() {
        this.supportedFormats = ['markdown', 'pdf', 'json', 'text'];
    }

    sanitizeErrorMessage(error) {
        const message = error && error.message ? error.message : String(error || 'Export operation failed');
        return message
            .replace(/(api[_-]?key|token|authorization)(\s*[:=]\s*)([A-Za-z0-9._~+/=-]+)/gi, '$1$2[redacted]')
            .slice(0, 240);
    }

    // Export analysis results
    async exportResults(analysisData, format = 'markdown') {
        if (!this.supportedFormats.includes(format)) {
            throw new Error(`Unsupported export format: ${format}`);
        }

        switch (format) {
            case 'markdown':
                return this.exportToMarkdown(analysisData);
            case 'pdf':
                return this.exportToPDF(analysisData);
            case 'json':
                return this.exportToJSON(analysisData);
            case 'text':
                return this.exportToText(analysisData);
            default:
                throw new Error(`Unknown format: ${format}`);
        }
    }

    // Export to Markdown
    exportToMarkdown(analysisData) {
        const { summary, metadata, cardData } = analysisData;
        const timestamp = new Date().toLocaleString();

        let markdown = `# Trello Card Analysis\n\n`;
        markdown += `**Generated:** ${timestamp}\n\n`;
        markdown += `**Card:** ${cardData.name}\n\n`;
        
        if (cardData.url) {
            markdown += `**Link:** [View in Trello](${cardData.url})\n\n`;
        }

        markdown += `---\n\n`;

        // Analysis Strategy
        markdown += `## Analysis Details\n\n`;
        markdown += `- **Strategy:** ${metadata.strategy}\n`;
        markdown += `- **AI Models Used:** ${metadata.modelsUsed.join(', ')}\n`;
        markdown += `- **Confidence:** ${Math.round(metadata.confidence * 100)}%\n`;
        markdown += `- **Cost:** $${metadata.totalCost.toFixed(4)}\n\n`;

        markdown += `---\n\n`;

        // Four-part analysis
        markdown += `## 📝 What this card is about\n\n`;
        markdown += `${summary.about}\n\n`;

        markdown += `## 📈 What has happened\n\n`;
        markdown += `${summary.history}\n\n`;

        markdown += `## 🎯 Current status\n\n`;
        markdown += `${summary.status}\n\n`;

        markdown += `## ✅ What's needed to complete\n\n`;
        markdown += `${summary.nextSteps}\n\n`;

        // Insights
        if (summary.insights && summary.insights.length > 0) {
            markdown += `## 💡 Key Insights\n\n`;
            summary.insights.forEach(insight => {
                markdown += `- ${insight}\n`;
            });
            markdown += `\n`;
        }

        // Card metadata
        markdown += `---\n\n`;
        markdown += `## Card Details\n\n`;
        
        if (cardData.labels && cardData.labels.length > 0) {
            markdown += `**Labels:** ${cardData.labels.map(l => l.name || l).join(', ')}\n\n`;
        }

        if (cardData.members && cardData.members.length > 0) {
            markdown += `**Members:** ${cardData.members.map(m => m.fullName || m).join(', ')}\n\n`;
        }

        if (cardData.due) {
            markdown += `**Due Date:** ${new Date(cardData.due).toLocaleDateString()}\n\n`;
        }

        if (cardData.checklistProgress) {
            markdown += `**Checklist Progress:** ${cardData.checklistProgress}\n\n`;
        }

        markdown += `---\n\n`;
        markdown += `*Generated by Summarize This - Multi-AI Trello Power-Up*\n`;

        this.downloadFile(markdown, `trello-analysis-${Date.now()}.md`, 'text/markdown');
        return markdown;
    }

    // Export to PDF (requires HTML conversion)
    async exportToPDF(analysisData) {
        // Generate HTML first
        const html = this.generateHTML(analysisData);
        
        // For browser environment, we'll use print functionality
        // In a production environment, you might want to use a library like jsPDF or pdfmake
        
        const printWindow = window.open('', '_blank');
        if (!printWindow) {
            throw new Error('Popup blocked. Please allow popups to print as PDF.');
        }
        printWindow.opener = null;
        printWindow.document.write(html);
        printWindow.document.close();
        
        // Trigger print dialog
        setTimeout(() => {
            printWindow.print();
        }, 500);

        return html;
    }

    // Generate HTML for PDF export
    generateHTML(analysisData) {
        const { summary, metadata, cardData } = analysisData;
        const timestamp = new Date().toLocaleString();
        const cardName = this.escapeHTML(cardData.name || 'Trello Card');
        const cardUrl = this.safeDisplayUrl(cardData.url);
        const strategy = this.escapeHTML(metadata.strategy || '');
        const modelList = this.escapeHTML((metadata.modelsUsed || []).join(', '));
        const about = this.escapeHTML(summary.about || '');
        const history = this.escapeHTML(summary.history || '');
        const status = this.escapeHTML(summary.status || '');
        const nextSteps = this.escapeHTML(summary.nextSteps || '');
        const insights = Array.isArray(summary.insights) ? summary.insights : [];

        return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Trello Card Analysis - ${cardName}</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
        }
        h1 {
            color: #0079bf;
            border-bottom: 3px solid #0079bf;
            padding-bottom: 10px;
        }
        h2 {
            color: #0079bf;
            margin-top: 30px;
            border-left: 4px solid #0079bf;
            padding-left: 15px;
        }
        .metadata {
            background: #f4f5f7;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .metadata p {
            margin: 5px 0;
        }
        .section {
            margin: 25px 0;
            padding: 20px;
            background: #f9f9f9;
            border-radius: 8px;
        }
        .insights {
            background: #fff3cd;
            padding: 15px;
            border-radius: 8px;
            border-left: 4px solid #ffc107;
        }
        .insights ul {
            margin: 10px 0;
            padding-left: 20px;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        @media print {
            body {
                padding: 20px;
            }
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <h1>📊 Trello Card Analysis</h1>
    
    <div class="metadata">
        <p><strong>Card:</strong> ${cardName}</p>
        <p><strong>Generated:</strong> ${this.escapeHTML(timestamp)}</p>
        ${cardUrl ? `<p><strong>Link:</strong> <a href="${cardUrl}" rel="noopener noreferrer">${cardUrl}</a></p>` : ''}
    </div>

    <div class="metadata">
        <p><strong>Strategy:</strong> ${strategy}</p>
        <p><strong>AI Models:</strong> ${modelList}</p>
        <p><strong>Confidence:</strong> ${Math.round(metadata.confidence * 100)}%</p>
        <p><strong>Cost:</strong> $${metadata.totalCost.toFixed(4)}</p>
    </div>

    <div class="section">
        <h2>📝 What this card is about</h2>
        <p>${about}</p>
    </div>

    <div class="section">
        <h2>📈 What has happened</h2>
        <p>${history}</p>
    </div>

    <div class="section">
        <h2>🎯 Current status</h2>
        <p>${status}</p>
    </div>

    <div class="section">
        <h2>✅ What's needed to complete</h2>
        <p>${nextSteps}</p>
    </div>

    ${insights.length > 0 ? `
    <div class="insights">
        <h2>💡 Key Insights</h2>
        <ul>
            ${insights.map(insight => `<li>${this.escapeHTML(insight)}</li>`).join('')}
        </ul>
    </div>
    ` : ''}

    <div class="footer">
        <p>Generated by Summarize This - Multi-AI Trello Power-Up</p>
    </div>
</body>
</html>
        `;
    }

    escapeHTML(value) {
        return String(value ?? '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    safeDisplayUrl(value) {
        if (!value) return '';

        try {
            const parsed = new URL(value);
            if (parsed.protocol !== 'https:') return '';
            return this.escapeHTML(parsed.href);
        } catch (error) {
            return '';
        }
    }

    // Export to JSON
    exportToJSON(analysisData) {
        const json = JSON.stringify(analysisData, null, 2);
        this.downloadFile(json, `trello-analysis-${Date.now()}.json`, 'application/json');
        return json;
    }

    // Export to plain text
    exportToText(analysisData) {
        const { summary, metadata, cardData } = analysisData;
        const timestamp = new Date().toLocaleString();

        let text = `TRELLO CARD ANALYSIS\n`;
        text += `${'='.repeat(50)}\n\n`;
        text += `Generated: ${timestamp}\n`;
        text += `Card: ${cardData.name}\n\n`;

        text += `ANALYSIS DETAILS\n`;
        text += `${'-'.repeat(50)}\n`;
        text += `Strategy: ${metadata.strategy}\n`;
        text += `AI Models: ${metadata.modelsUsed.join(', ')}\n`;
        text += `Confidence: ${Math.round(metadata.confidence * 100)}%\n`;
        text += `Cost: $${metadata.totalCost.toFixed(4)}\n\n`;

        text += `WHAT THIS CARD IS ABOUT\n`;
        text += `${'-'.repeat(50)}\n`;
        text += `${summary.about}\n\n`;

        text += `WHAT HAS HAPPENED\n`;
        text += `${'-'.repeat(50)}\n`;
        text += `${summary.history}\n\n`;

        text += `CURRENT STATUS\n`;
        text += `${'-'.repeat(50)}\n`;
        text += `${summary.status}\n\n`;

        text += `WHAT'S NEEDED TO COMPLETE\n`;
        text += `${'-'.repeat(50)}\n`;
        text += `${summary.nextSteps}\n\n`;

        if (summary.insights && summary.insights.length > 0) {
            text += `KEY INSIGHTS\n`;
            text += `${'-'.repeat(50)}\n`;
            summary.insights.forEach((insight, i) => {
                text += `${i + 1}. ${insight}\n`;
            });
            text += `\n`;
        }

        text += `${'='.repeat(50)}\n`;
        text += `Generated by Summarize This - Multi-AI Trello Power-Up\n`;

        this.downloadFile(text, `trello-analysis-${Date.now()}.txt`, 'text/plain');
        return text;
    }

    // Download file helper
    downloadFile(content, filename, mimeType) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    // Copy to clipboard
    async copyToClipboard(analysisData, format = 'markdown') {
        let content;
        
        switch (format) {
            case 'markdown':
                content = this.generateMarkdownText(analysisData);
                break;
            case 'text':
                content = this.generatePlainText(analysisData);
                break;
            default:
                content = this.generatePlainText(analysisData);
        }

        try {
            await navigator.clipboard.writeText(content);
            return true;
        } catch (error) {
            if (typeof console !== 'undefined' && console.warn) {
                console.warn(`Failed to copy to clipboard: ${this.sanitizeErrorMessage(error)}`);
            }
            return false;
        }
    }

    // Generate markdown text (without downloading)
    generateMarkdownText(analysisData) {
        const { summary, metadata, cardData } = analysisData;
        const timestamp = new Date().toLocaleString();

        let markdown = `# Trello Card Analysis\n\n`;
        markdown += `**Generated:** ${timestamp}\n`;
        markdown += `**Card:** ${cardData.name}\n\n`;
        
        markdown += `## 📝 What this card is about\n\n${summary.about}\n\n`;
        markdown += `## 📈 What has happened\n\n${summary.history}\n\n`;
        markdown += `## 🎯 Current status\n\n${summary.status}\n\n`;
        markdown += `## ✅ What's needed to complete\n\n${summary.nextSteps}\n\n`;

        if (summary.insights && summary.insights.length > 0) {
            markdown += `## 💡 Key Insights\n\n`;
            summary.insights.forEach(insight => {
                markdown += `- ${insight}\n`;
            });
        }

        return markdown;
    }

    // Generate plain text (without downloading)
    generatePlainText(analysisData) {
        const { summary, cardData } = analysisData;
        
        let text = `${cardData.name}\n\n`;
        text += `What this card is about:\n${summary.about}\n\n`;
        text += `What has happened:\n${summary.history}\n\n`;
        text += `Current status:\n${summary.status}\n\n`;
        text += `What's needed to complete:\n${summary.nextSteps}\n`;

        return text;
    }

    // Create export UI
    createExportUI(analysisData) {
        const exportMenu = document.createElement('div');
        exportMenu.className = 'export-menu';
        exportMenu.innerHTML = `
            <button class="export-btn" title="Export Analysis">
                📥 Export
            </button>
            <div class="export-dropdown">
                <button class="export-option" data-format="markdown">
                    📝 Download as Markdown
                </button>
                <button class="export-option" data-format="pdf">
                    📄 Print as PDF
                </button>
                <button class="export-option" data-format="json">
                    🔧 Download as JSON
                </button>
                <button class="export-option" data-format="text">
                    📋 Download as Text
                </button>
                <hr style="margin: 5px 0; border: none; border-top: 1px solid rgba(255,255,255,0.1);">
                <button class="export-option" data-action="copy">
                    📋 Copy to Clipboard
                </button>
            </div>
        `;

        // Add event listeners
        const btn = exportMenu.querySelector('.export-btn');
        const dropdown = exportMenu.querySelector('.export-dropdown');
        
        btn.addEventListener('click', () => {
            dropdown.classList.toggle('show');
        });

        exportMenu.querySelectorAll('.export-option').forEach(option => {
            option.addEventListener('click', async () => {
                const format = option.dataset.format;
                const action = option.dataset.action;

                if (action === 'copy') {
                    const success = await this.copyToClipboard(analysisData, 'markdown');
                    if (success) {
                        option.textContent = '✅ Copied!';
                        setTimeout(() => {
                            option.textContent = '📋 Copy to Clipboard';
                        }, 2000);
                    }
                } else if (format) {
                    await this.exportResults(analysisData, format);
                }

                dropdown.classList.remove('show');
            });
        });

        // Close dropdown when clicking outside
        document.addEventListener('click', (e) => {
            if (!exportMenu.contains(e.target)) {
                dropdown.classList.remove('show');
            }
        });

        return exportMenu;
    }
}

// Export for use in main application
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ExportManager;
}
